### PR TITLE
Update webglImageNodeProgram.js

### PR DESCRIPTION
**Pull request by weequ**
https://github.com/anvaka/VivaGraphJS/issues/34#issuecomment-253107796

### CODE REVIEW

**Comment by josephrocca** [comment]
Thanks for this! Here's a fixed version of the lib to make it easy for others (while we await anvaka's merge):

https://gist.github.com/josephrocca/a5e3bfb96665ef5e5499523e2cc71cb7

**Comment by joaquin-alc** [comment]
Please anvaka aprove this merge request!!

**Comment by anvaka** [comment]
published as `v0.11.0`

**Comment by joaquin-alc** [comment]
Yuju!!

**Pull request merged**
